nmcclain/CSCI4830-009

- 05-biz_models/05-slides.html
This pull request is for the homework assignment to improve the class notes. I saw a cool talk online about how Netflix maintains its microservices. It also goes into the Simian Army. I thought it would be a good addition to the slides about business models. 
-Taylor Andrews
> Added link to relevant Netflix microservices talk

- 13-projects2/13-slides.html
Added the link which gives the summary of why the Amazon S3 outage occurred
>  Added link for Amazon S3 outage postmortem

- Homework_Assignments.md
- projects/Emma_Montross_Mozilla.md
Sorry these are in the same PR!  
Added mission statement file in projects/ for HW2  
Added a separate .md file with a homework assignments list so students do not have to go searching through slides to find assignments and due dates.
> Emma Montross HW1 & HW2

- projects/Taylor_Andrews_ProjectBot.md
This pull request is for HW2. I added a mission statement for the ProjectBot project. 
-Taylor Andrews
> Created initial project mission statement

- projects/RYANRILEY_SCIKIT-LEARN.md
Adding the initial project proposal
> Ryan Riley Project Proposal

- projects/CassieSouza_freeCodeCamp.md
Added project mission statement
> Created CassieSouza_freeCodeCamp.md file

- projects/ParkerIllig_Liquipedia.md
My submission for HW2, which is a mission statement for my future work on the Liquipedia wiki sites.
> Parker Illig - Liquipedia Mission Statement (HW2)

- projects/YanLi_angular.js.md
> Yan Li Project Proposal

- projects/EricFossas_RunestoneServer.md
> Eric Fossas Project Plan Submission

- projects/SiddharthPant_will.md
Project proposal added in the projects folder with name Siddharth Pant
> added project proposal

- projects/PeilunZhang_GoGithub.md
Peilun's project proposal on Go-Github
* Project link:
* https://github.com/google/go-github
> Peilun's project proposal on Go-Github

- projects/TREVOR_WAKEMAN_SLACKBOT.md
> Added planned contribution

- 10-projects/chiehluntang_mottbot.md
added project for chiehlun tang
> added project

- projects/OliverHanna_ScikitLearn.md
Project Proposal for Oliver Hanna
> project proposal

- projects/KeyuChen_ReactProject
I find I have pull it to my own fork. The original pull request link "https://github.com/lgzh2003/CSCI4830-009/pull/1".
> Project wrong place

- Interesting_Links.md
Included a link to the podcast FLOSS Weekly.
> Added file for interesting links.

- Homework3Submissions.md
Some of us do not control our course project repositories. We need to provide our Hw3 and Hw4 repository links (Option 2 mentioned in the assignments file)
> Created a separate file for Homework3 submissions

- 13-projects2/13-slides.html
Adding several links that I found to be useful in deciding on my project.
> Riley HW1 - adding project resources to slides

- projects/Brian_Alfano_Scikit-learn.md
I believe I did **option 2** and created my own "hello world" repo and added a good repo name, description, readme, license, and contributing section.
> Homework 3 repo link added to my file.

- Homework3Submissions.md
Went ahead and added my HW3 submission to the Homework3Submissions.md list.
> HW3 Submission

- projects/ParkerIllig_Liquipedia.md
Added the link to my personal repo for homework 3.
> added hw3 repo link

- projects/ALIMULLASHAIK_ALEXA-SKILL.md
Hi Sir,
Updated file with HW 3 link.
> Updated with HW 3 link

- Homework3Submissions.md
I'm sorry that this is a late submission. I'm not sure how this got away from me. Please let me know if there are any issues with me submitting this now!
> Adding Tyler Lugger HW3 submission.

- Homework3Submissions.md
Had a link in my file in the projects directory. Also posting it here.
> Adding Link to my HW3

- Homework3Submissions.md
Hi, I found a mistake, I created a light weight "Todos app with react", so my project should belong to Option 2 rather than Option 1. In this case, I modified Option 1 to Option 2.
> Modify Option 1 to Option 2

- Homework_Assignments.md
> added due date for HW4

- projects/SiddharthPant_will.md
homework 4 done. Notes added in SiddharthPant_will.md in projects folder
> homework 4 done. Notes added in SiddharthPant_will.md in projects folder

- 23-automation/23-slides.html
- Add reference to quote
- Ensure consistent quote citations
- Fix typos
- Fix improperly referenced image
> Fix Lecture 4/17 slides

- projects/ALIMULLASHAIK_ALEXA-SKILL.md
Hi Sir,
Updated with HW 4 details.
> Updated with HW 4 details

- Homework3Submissions.md
Added a description to what I did for homework 4. Homework 4 is pretty much an "updated" homework 3. Therefore the link for homework 4 is the same as homework 3.
> Updated homework 3 link

- Homework3Submissions.md
Based on the email you sent me I left out my CI. So I added my Travis CI to the homework for full credit! Hope you like it! Also added screen shots to show that Travis CI passed and my tests passed.
> Updated Homework Submission

- 08-opensource_projs/08-slides.html
Update download times for Left-pad
> HW1: Update download times for Left-pad

- projects/KeyuChen_ReactProject.md
Hi, I use Travis CI for continues integration.
> add HW4 link

- Project_Presentations.md
> Add .md file for presentation

- projects/YanLi_CalenDay.md
add hw4 link in macdown file and add CI in my project.
> HW1 & HW4  YAN LI

- 15-implementing_agile/15-slides.html
Hi, I find there are two pictures introducing Extreme Programming(XP), I added several details about the XP including planning, managing, designing, coding and testing.
> Update 15-slides.html (Add details on XP)

- 14-agile/14-slides.html
Hi Sir,
I have added a slide under 14-Agile folder for HW1. 
Please merge this if you are okay with it.
Thanks.
My changes are follows.
In 14-Agile => 14-slides.html
Added below slide after slide, background-image: url(images/manifesto.png) 
12 Principles of Agile Manifesto are well documented in below link.  
https://www.agilealliance.org/agile101/12-principles-behind-the-agile-manifesto/
There are different methods and frameworks involved in Agile and all of them are explained in the link.
https://www.agilealliance.org/agile101/agile-glossary/
One of the interesting method is Kanban method and can find out more about the same in below link
https://www.agilealliance.org/glossary/kanban/
Scrm frequently comes up when we discuss about Agile and have you ever wondered, what is the …
> Added Hw 1

- 23-automation/23-slides.html
Inserted link for comparison across Travis, Circle and Codeship
> Updated slide 23 for hw1

- 20-chatops_sre/20-slides.html
- projects/AubreeLytwyn_CreateReactApp.md
> Lytwyn HW1, edited HW slides to include links and HW4/project

- 01-welcome/01-welcome.html
Added email contact to first slide of the class. Completing homework #1.
> added email to first slide

- projects/JESSICAPETTY_macWindows.md
Hi Ned!
I'm updating my HW 3 submission so you can easily find my update project. Thanks for a great semester!
PS a GitHub user I don't know starred my repo (not to brag ;) ) It feels really awesome, though, to see people engage with your ideas! Open source is an exciting word!
> update project file so Ned can find my updated project more easily

- 17-microservices_containers/17-slides.html
> Added an interesting fact about docker development

- projects/DylanMcKinney_SlackNavTools
just want to make sure you/anyone who wants to look at my slackbot have the right repo link
> Update to have proper project name/URL
